### ISSUE TITLE
DriverNotSupported: Driver __esModule is not supported

### ISSUE THREAD

**Issue by Ciboulette** [Slynova-Org/flydrive#100]
Hey,

 Im using ESM (https://www.npmjs.com/package/esm) and flydrive, when I try to run it in production I got:

```
{ /home/ubuntu/www/releases/725cf5a1ff04071eab0a9e12319e8d434b41df29/packages/api/node_modules/@slynova/flydrive/src/Exceptions/index.js:1
DriverNotSupported: Driver __esModule is not supported
    at Function.driver (/home/ubuntu/www/releases/725cf5a1ff04071eab0a9e12319e8d434b41df29/packages/api/node_modules/@slynova/flydrive/src/Exceptions/index.js:14:23)
    at Object.get (/home/ubuntu/www/releases/725cf5a1ff04071eab0a9e12319e8d434b41df29/packages/api/node_modules/@slynova/flydrive/src/Drivers/index.js:24:35) driver: '__esModule' }
```

Do you have an idea why?

**Comment by targos** [comment]
This issue is fixed on `develop` (future v1.0.0)
