### ISSUE TITLE
fs_1.promises.opendir is not a function

### ISSUE THREAD

**Issue by AntonLugtenburg** [Slynova-Org/flydrive#161]
Hi,

i'm running Node v.14  and i get this error trying to delete a file.

```
{
  "errors": [
    {
      "message": "E_UNKNOWN: An unknown error happened with the file 81837c5d-3345-483a-8a48-1b576fafcd41.
Please open an issue at https://github.com/Slynova-Org/flydrive/issues

Error code: undefined
Original stack:
TypeError: fs_1.promises.opendir is not a function
    at LocalFileSystemStorage._flatDirIterator (/var/www/vhosts/.../node_modules/@slynova/flydrive/build/LocalFileSystemStorage.js:221:45)
    at _flatDirIterator.next (<anonymous>)    at FilesService.<anonymous> (/var/www/vhosts/.../node_modules/directus/dist/services/files.js:165:108)
    at Generator.next (<anonymous>)
   at fulfilled (/var/www/vhosts/.../node_modules/directus/dist/services/files.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

Can someone help me ? Thank you very much...

**Comment by RomainLanz** [comment]
Hey @AntonLugtenburg! 👋 

That's interesting because the token `fs_1.promises.opendir` is pointing to a native module (`fs`).
Are you sure to use Node.js 14 when running your code?

**Comment by AntonLugtenburg** [comment]
Hi, yes, im running 14.15.5. I'm also confused why it throws this exception ... i can also call the function via cli

**Comment by targos** [comment]
Can you share the code that you run which gives this error?

**Comment by AntonLugtenburg** [comment]
https://github.com/directus/directus/issues/3998
 It happens when trying to delete a file in directus. Its not my own code :(
